---
# tasks file for postgresql# tasks/pg_config.yml

- name: ensure logs directory exists
  file: state=directory path="{{ pg_log_directory }}" owner="{{ pg_user }}" group="{{ pg_group }}" mode=0700
  tags: postgresql,postgresql-config

- name: be sure postgresql is configured
  template: src="postgresql.conf-{{ pg_version }}.j2" dest="{{ pg_config_path }}/postgresql.conf" backup=yes
  notify:
    - reload postgresql
  tags: postgresql,postgresql-config

- name: be sure pg_ident is configured
  template: src=pg_ident.conf.j2 dest="{{ pg_config_path }}/pg_ident.conf" backup=yes
  notify:
    - reload postgresql
  tags: postgresql,postgresql-config

- name: be sure pg_hba is configured
  template: src=pg_hba.conf.j2 dest="{{ pg_config_path }}/pg_hba.conf" backup=yes
  notify:
    - reload postgresql
  tags: postgresql,postgresql-config

- name: be sure postgresqld is running and enabled
  service: name="{{ pg_service }}" state=started enabled=yes
  tags: postgresql,postgresql-config

