---
- name: Postgresql | Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags: postgresql,includes

- name: Postgresql | Setting OS specific variables
  set_fact:
    pg_major_release: "{{ pg_major_release if pg_major_release is defined else __pg_major_release }}"
    pg_minor_release: "{{ pg_minor_release if pg_minor_release is defined else __pg_minor_release }}"
    pg_packages: "{{ pg_packages if pg_packages is defined else __pg_packages }}"
    pg_config_directory: "{{ pg_config_directory if pg_config_directory is defined else __pg_config_directory }}"
    pg_data_directory: "{{ pg_data_directory if pg_data_directory is defined else __pg_data_directory }}"
    pg_log_directory: "{{ pg_log_directory if pg_log_directory is defined else __pg_log_directory }}"
  tags: postgresql,includes

- name: Postgresql |install postgresql
  include_tasks: install.yml
  tags: postgresql,postgresql-install

- name: Postgresql | configure postgresql
  include_tasks: config.yml
  tags: postgresql,postgresql-config
