# tasks/main.yml
---
- name: Postgresql | Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags: postgresql,includes

  #- name: Postgresql | check/create ssl snakeoil certs
  #include_tasks: ssl.yml
  #tags: postgresql,postgresql-ssl

- name: Postgresql |install postgresql
  include_tasks: install.yml
  tags: postgresql,postgresql-install

  #- name: Postgresql | configure postgresql
  #  include_tasks: config.yml
  #  tags: postgresql,postgresql-config
    
