---
# tasks file for postgresql# tasks/pg_install.yml

- name: be sure postgresql repo packages configured
  yum: name="{{ pg_url_rpm }}" state=present
  when: ansible_os_family == 'RedHat'
  tags: postgresql,postgresql-install

- name: be sure postgresql+postgis is installed (yum)
  yum: name="{{ item }}" state=present 
  with_items: "{{ pg_packages }}"
  when: ansible_os_family == 'RedHat'
  tags: postgresql,postgresql-install

- name: be sure postgresql+postgis is installed (apt)
  apt: name="{{ item }}" state=present update_cache=yes
  with_items: "{{ pg_packages }}"
  when: ansible_os_family == 'Debian'
  tags: postgresql,postgresql-install

# Soft fail if cluster exists
- name: init database (centos)
  command: "/usr/pgsql-{{ pg_version }}/bin/postgresql-{{ pg_version }}-setup initdb"
  register: initdb_result
  failed_when: not  "'not empty' in initdb_result.stdout"
  when: ansible_os_family == 'RedHat'
  tags: postgresql,postgresql-install

