---
# tasks file for postgresql# tasks/pg_os_parameters.yml
# https://www.postgresql.org/docs/9.6/static/kernel-resources.html
#
- name: max fs files
  sysctl: name="fs.file-max" value="{{ pg_os_fs_file_max }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config
- name: kernel semaphores
  sysctl: name="kernel.sem" value="{{ pg_os_kernel_sem }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config
- name: maximum size of shared memory segment
  sysctl: name="kernel.shmmax" value="{{ pg_os_kernel_shmmax }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config
- name: total amount of shared memory available
  sysctl: name="kernel.shmall" value="{{ pg_os_kernel_shmall }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config

# dirty pages control
# Low write performance on SLES 11/12 servers with large RAM
# https://www.suse.com/es-es/support/kb/doc/?id=7010287

- name: max of dirty system memory
  sysctl: name="vm.dirty_bytes" value="{{ pg_os_vm_dirty_bytes }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config
- name: dirty system memory at which background writeback will start
  sysctl: name="vm.dirty_background_bytes" value="{{ pg_os_vm_dirty_background_bytes }}" sysctl_set=yes state=present reload=yes
  tags: postgresql,postgresql-os-config

