# handlers/main.yml
 - name: restart postgresql
   systemd: 
    name: "{{ pg_service }}" 
    state: restarted
 - name: reload postgresql
   service: 
    name: "{{ pg_service }}" 
    state: reloaded
