---
pg_major_release: "9.6"
pg_minor_release: "15-1.pgdg90+1"
pg_packages:
  - "{{ pg_basename }}={{ pg_major_release }}.{{ pg_minor_release }}"
  - "postgresql-contrib-{{ pg_basename_version }}={{ pg_major_release }}.{{ pg_minor_release }}"

